# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/fpga/xilinix/projects/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/fpga/xilinix/projects/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/fpga/xilinix/projects/project_1/project_1.srcs/sources_1/new/twotoone.v
read_xdc D:/fpga/xilinix/projects/project_1/project_1.srcs/constrs_1/imports/projects/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/fpga/xilinix/projects/project_1/project_1.srcs/constrs_1/imports/projects/Basys3_Master.xdc]

catch { write_hwdef -file nbasic.hwdef }
synth_design -top nbasic -part xc7a35tcpg236-1
write_checkpoint -noxdef nbasic.dcp
catch { report_utilization -file nbasic_utilization_synth.rpt -pb nbasic_utilization_synth.pb }
